### ISSUE TITLE
Count repos without secondary commit (double count).

### ISSUE THREAD

**Issue by synchook** [synchook/synchook#5]
So in a scenario where I want to see my daily commit's updated even on repos where the commit will already be counted by GitHub... 
Such as using the synchook feature below to see my daily commits in real-time...

![image](https://user-images.githubusercontent.com/123592097/221653273-8ab37808-6723-464a-8de3-e1e9bef96f16.png)

And viewing commits via the dashboard, etc.

Right now, using synchook will result in a double count on repos that fall outside of the original intent (i.e. private, local, other provider). So on those repos, there should be some way to exclude them from making that secondary commit.

A client side configuration key is likely the best way since it won't be dependent upon the backend... or both places for greater mobility?

**Comment by june07** [comment]
Done

Frontend update here: https://github.com/synchook/synchook/commit/15cea445b1abac920f04903b02ee80344b38f307
Backend update here: https://github.com/synchook/june07/blob/main/gitlab.com-pads-/2-27-2023/ab1fe8ac32927ab7729d80f063495c60e3563af1
